export const mechanisms = [
  {
    id: "standard-attention",
    date: "2017-06-12",
    name: "Scaled dot-product attention",
    label: "The exact baseline",
    family: "exactness",
    problem: "Recurrent models made long-range dependencies slow and difficult to parallelize.",
    move: "Every query scores every key, applies softmax, then mixes the values.",
    buys: "Exact, content-dependent global retrieval and highly parallel training.",
    gives: "An N x N score matrix and a growing KV cache during decoding.",
    choose: "Use when quality and unrestricted token-to-token access matter more than long-context cost.",
    next: "Sparse patterns, windows and linear state attack its quadratic bill; MQA attacks its cache bill.",
    compute: "O(N²d)", cache: "O(NHkv d)", exactness: "Exact", context: "Training-limited",
    sourceTitle: "Attention Is All You Need", sourceUrl: "https://arxiv.org/abs/1706.03762"
  },
  {
    id: "sinusoidal",
    date: "2017-06-12",
    name: "Sinusoidal positions",
    label: "Order without a table",
    family: "position",
    problem: "Self-attention is permutation-equivariant: without position, it reads a set rather than a sequence.",
    move: "Add deterministic sine and cosine signals at multiple frequencies to token embeddings.",
    buys: "No learned position table and a formula defined at unseen indices.",
    gives: "Being defined out of range does not guarantee useful length extrapolation.",
    choose: "Use as a simple parameter-free absolute position baseline.",
    next: "Learned tables improve adaptation; RoPE and ALiBi inject relative distance inside attention.",
    compute: "O(Nd)", cache: "No extra KV", exactness: "Exact attention", context: "Formula extrapolates",
    sourceTitle: "Attention Is All You Need", sourceUrl: "https://arxiv.org/abs/1706.03762"
  },
  {
    id: "learned-absolute",
    date: "2018-06-11",
    name: "Learned absolute positions",
    label: "Let the model learn the map",
    family: "position",
    problem: "Fixed sinusoids may be a poor inductive bias for a particular language model and dataset.",
    move: "Learn one vector for each position and add it to the token embedding, as in GPT.",
    buys: "Flexible position-specific features learned directly from data.",
    gives: "A hard table boundary; unseen rows are absent or untrained, so extrapolation is weak.",
    choose: "Use for fixed-length settings where the maximum sequence is known.",
    next: "Relative schemes and RoPE remove dependence on a finite learned table.",
    compute: "O(Nd)", cache: "Position table", exactness: "Exact attention", context: "Hard maximum",
    sourceTitle: "Improving Language Understanding by Generative Pre-Training", sourceUrl: "https://cdn.openai.com/research-covers/language-unsupervised/language_understanding_paper.pdf"
  },
  {
    id: "sparse-transformer",
    date: "2019-04-23",
    name: "Sparse Transformer",
    label: "Structure the N x N matrix",
    family: "compute",
    problem: "Full attention becomes prohibitively expensive on images, audio and long text.",
    move: "Use fixed strided and local factorizations instead of evaluating every token pair.",
    buys: "Sub-quadratic attention and sequences with tens of thousands of steps.",
    gives: "A fixed pattern can miss content that lies outside its allowed edges.",
    choose: "Use when the data has predictable local or strided structure.",
    next: "Content-based routing and learned top-k selection try to choose edges dynamically.",
    compute: "O(N√N)", cache: "Pattern-dependent", exactness: "Sparse exact edges", context: "Long",
    sourceTitle: "Generating Long Sequences with Sparse Transformers", sourceUrl: "https://arxiv.org/abs/1904.10509"
  },
  {
    id: "mqa",
    date: "2019-11-06",
    name: "Multi-Query Attention",
    label: "One shared KV head",
    family: "memory",
    problem: "Autoregressive decoding repeatedly loads a large K/V cache for every attention head.",
    move: "Keep many query heads but share one key head and one value head across them.",
    buys: "Much smaller KV cache and lower memory bandwidth during decoding.",
    gives: "Less head-specific KV capacity and sometimes lower model quality.",
    choose: "Use when serving throughput and memory dominate and some quality trade-off is acceptable.",
    next: "GQA introduces several shared KV groups as a middle ground.",
    compute: "Still O(N²d)", cache: "Lowest of MHA family", exactness: "Exact", context: "Cache-limited",
    sourceTitle: "Fast Transformer Decoding: One Write-Head is All You Need", sourceUrl: "https://arxiv.org/abs/1911.02150"
  },
  {
    id: "explicit-top-k",
    date: "2019-12-25",
    name: "Explicit top-k attention",
    label: "Keep only the strongest edges",
    family: "retrieval",
    problem: "Dense attention spends capacity and compute on many irrelevant tokens.",
    move: "Explicitly select the most relevant segments or keys before mixing their values.",
    buys: "Concentrated attention and a sparse final computation.",
    gives: "Naive top-k still scores every key first; approximate selectors can miss evidence.",
    choose: "Use when relevance is highly concentrated and selection can be made cheaply.",
    next: "Routing and DeepSeek's lightweight indexer make proposal cheaper than full scoring.",
    compute: "O(N²) if naive", cache: "Can remain O(N)", exactness: "Top-k approximation", context: "Long if indexed",
    sourceTitle: "Explicit Sparse Transformer", sourceUrl: "https://arxiv.org/abs/1912.11637"
  },
  {
    id: "sliding-window",
    date: "2020-04-10",
    name: "Sliding-window attention",
    label: "Locality as a budget",
    family: "compute",
    problem: "Long documents cannot afford unrestricted global attention at every position.",
    move: "Each token attends to a fixed local window, with optional task-specific global tokens.",
    buys: "O(Nw) compute, predictable kernels and bounded streaming cache.",
    gives: "Information beyond the window needs depth, global tokens or a separate memory path.",
    choose: "Use for local structure, streaming, or long documents with a few global landmarks.",
    next: "Attention sinks stabilize streaming; hybrid models add occasional global retrieval.",
    compute: "O(Nw)", cache: "O(w)", exactness: "Exact in window", context: "Local receptive field",
    sourceTitle: "Longformer: The Long-Document Transformer", sourceUrl: "https://arxiv.org/abs/2004.05150"
  },
  {
    id: "linear-attention",
    date: "2020-06-29",
    name: "Linear attention",
    label: "Turn history into state",
    family: "compute",
    problem: "The quadratic attention matrix prevents efficient processing of very long sequences.",
    move: "Replace softmax with kernel feature maps and reassociate products into a recurrent state S = Σ φ(K)Vᵀ.",
    buys: "Linear sequence complexity and constant-size recurrent state during decoding.",
    gives: "No exact softmax competition or query-specific distribution over all past tokens.",
    choose: "Use when bounded memory and streaming speed matter more than exact retrieval.",
    next: "The delta rule improves overwriting; hybrid layers restore occasional exact access.",
    compute: "O(Nd²)", cache: "O(d²) state", exactness: "Approximate", context: "Unbounded stream",
    sourceTitle: "Transformers are RNNs", sourceUrl: "https://arxiv.org/abs/2006.16236"
  },
  {
    id: "bigbird",
    date: "2020-07-28",
    name: "BigBird",
    label: "Local + random + global",
    family: "compute",
    problem: "Purely local sparse patterns may lose the global connectivity needed for general sequence functions.",
    move: "Combine sliding windows, random edges and a small set of global tokens.",
    buys: "Linear sparse attention with theoretical connectivity and longer documents.",
    gives: "More architectural complexity and approximate access compared with dense attention.",
    choose: "Use when long documents need both local structure and a few global routes.",
    next: "Learned routing replaces hand-designed random and global patterns.",
    compute: "O(N)", cache: "Sparse O(N)", exactness: "Sparse", context: "Long",
    sourceTitle: "Big Bird: Transformers for Longer Sequences", sourceUrl: "https://arxiv.org/abs/2007.14062", bonus: true
  },
  {
    id: "delta-rule",
    date: "2021-02-22",
    name: "Delta rule / DeltaNet",
    label: "Correct memory, don't only add",
    family: "memory",
    problem: "Additive linear-attention state cannot cleanly replace an obsolete key-value association.",
    move: "Read the current value for a key, compute the error, then write only the correction.",
    buys: "Targeted overwriting and better associative recall in fixed-size state.",
    gives: "Finite state still compresses history and can suffer interference.",
    choose: "Use for streaming models that need mutable associative memory.",
    next: "Gated DeltaNet adds learned forgetting for broader memory control.",
    compute: "O(Nd²)", cache: "O(d²) state", exactness: "Compressed state", context: "Unbounded stream",
    sourceTitle: "Linear Transformers Are Secretly Fast Weight Programmers", sourceUrl: "https://arxiv.org/abs/2102.11174"
  },
  {
    id: "rope",
    date: "2021-04-20",
    name: "RoPE",
    label: "Position inside Q · K",
    family: "position",
    problem: "Absolute position additions do not express relative distance directly in attention scores.",
    move: "Rotate query and key dimension pairs by position-dependent phases.",
    buys: "Relative displacement appears naturally in the dot product without a learned table.",
    gives: "Positions far beyond training produce unfamiliar phases and degraded attention.",
    choose: "Use as a strong modern positional baseline with efficient implementations.",
    next: "NTK scaling, YaRN and other extensions recalibrate frequencies beyond training length.",
    compute: "O(Nd)", cache: "Small trig cache", exactness: "Exact attention", context: "Train-range sensitive",
    sourceTitle: "RoFormer: Enhanced Transformer with Rotary Position Embedding", sourceUrl: "https://arxiv.org/abs/2104.09864"
  },
  {
    id: "alibi",
    date: "2021-08-27",
    name: "ALiBi",
    label: "Distance as a score penalty",
    family: "position",
    problem: "Models trained at short lengths struggle when tested on longer sequences.",
    move: "Subtract a head-specific linear distance bias directly from attention logits.",
    buys: "Simple length extrapolation without learned position embeddings.",
    gives: "A fixed recency bias can disadvantage distant evidence and is less flexible than learned geometry.",
    choose: "Use when training short and testing longer is central and recency is useful.",
    next: "RoPE extensions preserve richer phase geometry while stretching context.",
    compute: "O(N²d)", cache: "No position table", exactness: "Exact + bias", context: "Extrapolative",
    sourceTitle: "Train Short, Test Long", sourceUrl: "https://arxiv.org/abs/2108.12409"
  },
  {
    id: "flashattention",
    date: "2022-05-27",
    name: "FlashAttention",
    label: "Move fewer bytes, keep the math",
    family: "systems",
    problem: "Attention can be slow because GPU memory traffic, not arithmetic alone, is the bottleneck.",
    move: "Tile exact attention so intermediate matrices stay in fast on-chip memory.",
    buys: "Exact attention with lower memory use and faster wall-clock execution.",
    gives: "It does not remove quadratic arithmetic or the linear KV-cache growth of decoding.",
    choose: "Use almost whenever dense attention runs on supported accelerators.",
    next: "Sparse FlashAttention and hardware-aware kernels combine IO efficiency with fewer edges.",
    compute: "O(N²d)", cache: "Unchanged KV", exactness: "Exact", context: "Longer in practice",
    sourceTitle: "FlashAttention", sourceUrl: "https://arxiv.org/abs/2205.14135", bonus: true
  },
  {
    id: "gqa",
    date: "2023-05-22",
    name: "Grouped-Query Attention",
    label: "The practical cache compromise",
    family: "memory",
    problem: "MQA saves memory but one shared KV head can reduce quality.",
    move: "Divide query heads into groups, each sharing one key/value head.",
    buys: "Quality close to MHA with decoding speed and cache size close to MQA.",
    gives: "KV cache still grows linearly with context and the grouping is another design choice.",
    choose: "Use as a production baseline for autoregressive LLM serving.",
    next: "MLA compresses the KV representation itself rather than only reducing head count.",
    compute: "O(N²d)", cache: "Between MHA & MQA", exactness: "Exact", context: "Cache-limited",
    sourceTitle: "GQA: Training Generalized Multi-Query Transformer Models from Multi-Head Checkpoints", sourceUrl: "https://arxiv.org/abs/2305.13245"
  },
  {
    id: "ntk-scaling",
    date: "2023-06-29",
    name: "NTK-aware RoPE scaling",
    label: "Stretch frequencies unevenly",
    family: "position",
    problem: "Uniformly interpolating every RoPE frequency harms nearby-token resolution.",
    move: "Change RoPE's base so lower frequencies stretch more than high-frequency local features.",
    buys: "Useful context extension with little or no fine-tuning in community experiments.",
    gives: "An empirical community technique with weaker original evaluation than a full paper.",
    choose: "Use for inexpensive extension of an existing RoPE checkpoint, followed by careful evaluation.",
    next: "YaRN combines interpolation ideas with attention-temperature correction and efficient fine-tuning.",
    compute: "Unchanged", cache: "Unchanged", exactness: "Exact + rescaled PE", context: "Extended",
    sourceTitle: "Original bloc97 release", sourceUrl: "https://www.reddit.com/r/LocalLLaMA/comments/14lz7j5/ntkaware_scaled_rope_allows_llama_models_to_have/"
  },
  {
    id: "yarn",
    date: "2023-08-31",
    name: "YaRN",
    label: "Efficient RoPE extension",
    family: "position",
    problem: "Existing RoPE extensions require too much long-context fine-tuning or degrade short-context quality.",
    move: "Blend frequency interpolation strategies and correct attention magnitude during extension.",
    buys: "Longer usable context with fewer training tokens and steps.",
    gives: "Still needs calibration/evaluation and does not reduce attention or KV-cache complexity.",
    choose: "Use to extend an existing RoPE model when retraining from scratch is impractical.",
    next: "DroPE questions whether explicit position embeddings must remain after training at all.",
    compute: "Unchanged", cache: "Unchanged", exactness: "Exact + rescaled PE", context: "Extended",
    sourceTitle: "YaRN: Efficient Context Window Extension of Large Language Models", sourceUrl: "https://arxiv.org/abs/2309.00071"
  },
  {
    id: "attention-sinks",
    date: "2023-09-29",
    name: "Attention sinks",
    label: "Keep the first anchors",
    family: "memory",
    problem: "A pure rolling window collapses once early high-attention tokens are evicted.",
    move: "Retain a few initial sink tokens alongside the recent sliding window.",
    buys: "Stable streaming for millions of tokens with bounded cache.",
    gives: "It supports continuity, not exact recall of arbitrary evicted details.",
    choose: "Use for streaming generation where bounded memory matters more than full-history retrieval.",
    next: "External retrieval or hybrid sparse attention restores selective access to distant content.",
    compute: "O(Nw)", cache: "O(w + sinks)", exactness: "Windowed", context: "Infinite stream",
    sourceTitle: "Efficient Streaming Language Models with Attention Sinks", sourceUrl: "https://arxiv.org/abs/2309.17453"
  },
  {
    id: "mla",
    date: "2024-05-07",
    name: "Multi-head Latent Attention",
    label: "Compress K and V together",
    family: "memory",
    problem: "Even GQA's smaller KV cache grows linearly and limits batch size at long context.",
    move: "Store a low-rank latent representation from which head-specific K/V information is recovered.",
    buys: "A dramatically smaller KV cache while retaining multi-head expressiveness.",
    gives: "More complex projections, specialized kernels and potential loss through compression.",
    choose: "Use for large-scale serving where KV memory is the dominant cost.",
    next: "DeepSeek sparse attention reduces which compressed positions are read as well.",
    compute: "Dense attention remains", cache: "Compressed latent O(N)", exactness: "Latent compression", context: "128K reported",
    sourceTitle: "DeepSeek-V2: A Strong, Economical, and Efficient Mixture-of-Experts Language Model", sourceUrl: "https://arxiv.org/abs/2405.04434"
  },
  {
    id: "gated-deltanet",
    date: "2024-12-09",
    name: "Gated DeltaNet",
    label: "Targeted write + global forget",
    family: "memory",
    problem: "Delta updates overwrite a key precisely, but fixed-state memory also needs adaptive global forgetting.",
    move: "Combine delta-rule correction with a learned decay gate and hardware-efficient parallel training.",
    buys: "Better memory control, recall and long-context performance than additive linear state.",
    gives: "Still compresses history into finite state and cannot guarantee exact token retrieval.",
    choose: "Use for efficient recurrent layers inside hybrid long-context models.",
    next: "Hybrid schedules pair state layers with sparse or windowed exact attention.",
    compute: "O(Nd²)", cache: "O(d²) state", exactness: "Compressed state", context: "Unbounded stream",
    sourceTitle: "Gated Delta Networks", sourceUrl: "https://arxiv.org/abs/2412.06464"
  },
  {
    id: "deepseek-sparse",
    date: "2025-09-29",
    name: "DeepSeek Sparse Attention",
    label: "A cheap index before an expensive read",
    family: "retrieval",
    problem: "Top-k attention saves little if selecting the top keys already requires full expensive scoring.",
    move: "A lightweight FP8 indexer scores compressed keys, then full attention reads only selected tokens.",
    buys: "Fine-grained content-based sparsity with efficient long-context kernels.",
    gives: "Approximate selection may miss evidence; the indexer itself still has a cost.",
    choose: "Use for very long context when content routing outperforms fixed windows.",
    next: "V4 combines sparse reads with explicit sequence and cache compression.",
    compute: "Indexer + O(Nk)", cache: "Sparse MLA", exactness: "Approximate selection", context: "128K+",
    sourceTitle: "DeepSeek-V3.2-Exp release", sourceUrl: "https://github.com/deepseek-ai/DeepSeek-V3.2-Exp"
  },
  {
    id: "drope",
    date: "2025-12-13",
    name: "DroPE",
    label: "Position as temporary scaffolding",
    family: "position",
    problem: "Explicit positional embeddings help training but become an out-of-distribution bottleneck beyond training length.",
    move: "Remove positional embeddings after pretraining, then briefly recalibrate at the original context length.",
    buys: "Zero-shot context extension without expensive long-context fine-tuning.",
    gives: "Recalibration is still required and the result does not reduce quadratic attention compute.",
    choose: "Use when extending a pretrained model whose positional encoding is the main ceiling.",
    next: "Future models may treat explicit position as training support rather than permanent architecture.",
    compute: "Unchanged", cache: "Unchanged", exactness: "Exact, no explicit PE", context: "Zero-shot extended",
    sourceTitle: "Extending the Context of Pretrained LLMs by Dropping Their Positional Embeddings", sourceUrl: "https://arxiv.org/abs/2512.12167"
  },
  {
    id: "deepseek-v4",
    date: "2026-04-24",
    name: "DeepSeek V4 CSA / HCA",
    label: "Compress the sequence, then retrieve",
    family: "hybrid",
    problem: "At million-token context, both the number of stored positions and the cost of selecting/reading them become dominant.",
    move: "Combine compressed representations, local uncompressed windows, learned sparse indexing and heavily compressed layers.",
    buys: "Much lower long-context inference FLOPs and KV cache than dense MLA alone.",
    gives: "Multiple lossy stages, complex kernels and harder diagnosis when retrieval fails.",
    choose: "Use at extreme context where dense exact access is economically impossible.",
    next: "Expect adaptive hybrids that spend exact attention only where uncertainty demands it.",
    compute: "Hybrid sub-quadratic", cache: "Strongly compressed", exactness: "Hybrid approximate", context: "1M",
    sourceTitle: "DeepSeek V4 official release", sourceUrl: "https://www.deepseek.com/en/transparency/"
  }
];

export const familyMeta = {
  exactness: { label: "Exactness", color: "#f5c451" },
  position: { label: "Position", color: "#b79cff" },
  compute: { label: "Compute", color: "#66d9c6" },
  memory: { label: "KV / memory", color: "#ff8066" },
  retrieval: { label: "Retrieval", color: "#58a9ff" },
  systems: { label: "Systems", color: "#e7eaef" },
  hybrid: { label: "Hybrid", color: "#ff70bd" }
};

export const requiredIds = [
  "standard-attention", "learned-absolute", "sinusoidal", "rope", "alibi",
  "mqa", "gqa", "sliding-window", "attention-sinks", "ntk-scaling", "yarn",
  "linear-attention", "delta-rule", "gated-deltanet", "mla", "sparse-transformer",
  "explicit-top-k", "deepseek-sparse", "deepseek-v4", "drope"
];
